name: Android Build Release

on:
    pull_request:
    push:
        branches:
            - 'develop'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout Commit
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Decrypt secret files
              env:
                INPUT_FILES: ./android/release.keystore.gpg
              run: |
                  for encrypted_file in ${INPUT_FILES//,/ }
                  do
                    gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --output "${encrypted_file%.*}" "$encrypted_file"
                  done

            - name: Get React Native Arsenal
              run: |
                  git clone https://gitlab.com/nepware-internals/react-native-arsenal.git src/vendor/react-native-arsenal

            - name: Gradle Wrapper Validation
              uses: gradle/wrapper-validation-action@v1

            - name: Cache Ruby gems
              uses: actions/cache@v3
              with:
                  path: android/vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '11'
                  cache: 'gradle'

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: '**/yarn.lock'

            - name: Install Dependencies
              run: |
                  yarn install --non-interactive
                  echo MAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN >> ./android/gradle.properties

            - name: Run Fastlane
              uses: maierj/fastlane-action@v2.2.0
              with:
                  skip-tracking: true
                  lane: 'build'
                  subdirectory: 'android'
                  bundle-install-path: vendor/bundle
              env:
                  FASTLANE_HIDE_CHANGELOG: true

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: apk
                  path: |
                    android/app/build/outputs/apk/release
                  retention-days: 14
