name: IOS Build Release

concurrency:
  group: build-ios-${{ github.ref }}
  cancel-in-progress: true

on:
    pull_request:
    push:
        branches:
            - 'develop'
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build:
        runs-on: macOS-13
        environment:
            name: ${{ github.ref_type == 'tag' && 'production' || 'staging' }}

        steps:
            - name: Checkout Commit
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Export secrets
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Export vars
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(vars) }}

            - name: Get React Native Arsenal
              run: |
                  git clone https://gitlab.com/nepware-internals/react-native-arsenal.git src/vendor/react-native-arsenal

            - name: Build Cache
              uses: mikehardy/buildcache-action@v2

            - name: Cache Pods
              uses: actions/cache@v3
              with:
                path: |
                  ios/Pods
                  ~/Library/Caches/CocoaPods
                  ~/.cocoapods
                key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
                restore-keys: |
                  ${{ runner.os }}-pods-

            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.0'
                bundler-cache: true
                working-directory: 'ios'

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: '**/yarn.lock'

            - name: Install Dependencies
              run: |
                  yarn install --non-interactive

            - name: Run Fastlane
              uses: maierj/fastlane-action@v3.0.0
              with:
                  lane: ${{ github.ref_type == 'tag' && 'beta' || 'build' }}
                  subdirectory: 'ios'
              env:
                  FASTLANE_HIDE_CHANGELOG: true

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ipa
                  path: |
                    ios/*.ipa
                  retention-days: 14
